### PR TITLE
fix: 🐛 support Shadow DOM

### LINKED ISSUE #31: To support Shadow DOM
### Describe the feature in detail (code, mocks, or screenshots encouraged)

The component is failed to be used in a Shadow DOM.

### What type of pull request would this be?

Enhancement

### Provide relevant links or additional information.

_No response_

### PR DESCRIPTION
**Pull request by songpola**
See https://github.com/svecosystem/paneforge/issues/31#issuecomment-2980122867

Fixes #31

### CODE REVIEW

**Comment by songpola** [comment]
I've done the refactoring, and I can confirm the handle is working in Shadow DOM now!

File: packages/paneforge/src/lib/internal/helpers.ts [hunk 1]
```diff
@@ -54,42 +55,51 @@ export function updateResizeHandleAriaValues({
...
+export function getResizeHandleElementsForGroup(
+	groupId: string,
+	domContext: DOMContext
+): HTMLElement[] {
 	if (!isBrowser) return [];
 	return Array.from(
-		doc.querySelectorAll(`[data-pane-resizer-id][data-pane-group-id="${groupId}"]`)
+		domContext.querySelectorAll(
+			`[data-pane-resizer-id][data-pane-group-id="${groupId}"]`
+		) as NodeListOf<HTMLElement>
```
Comment (songpola) [inline packages/paneforge/src/lib/internal/helpers.ts:66]: This one...

File: packages/paneforge/src/lib/internal/helpers.ts [hunk 2]
```diff
@@ -280,16 +290,18 @@ export function validatePaneGroupLayout({
 	return nextLayout;
 }
 
-export function getPaneGroupElement(id: string, doc: Document): HTMLElement | null {
+export function getPaneGroupElement(id: string, domContext: DOMContext): HTMLElement | null {
 	if (!isBrowser) return null;
-	const element = doc.querySelector<HTMLElement>(`[data-pane-group][data-pane-group-id="${id}"]`);
+	const element = domContext.querySelector(
+		`[data-pane-group][data-pane-group-id="${id}"]`
+	) as HTMLElement;
```
Comment (songpola) [inline packages/paneforge/src/lib/internal/helpers.ts:297]: This...

File: packages/paneforge/src/lib/internal/helpers.ts [hunk 3]
```diff
@@ -280,16 +290,18 @@ export function validatePaneGroupLayout({
...
 	if (element) return element;
 	return null;
 }
 
-export function getResizeHandleElement(id: string, doc: Document): HTMLElement | null {
+export function getResizeHandleElement(id: string, domContext: DOMContext): HTMLElement | null {
 	if (!isBrowser) return null;
-	const element = doc.querySelector<HTMLElement>(`[data-pane-resizer-id="${id}"]`);
+	const element = domContext.querySelector(`[data-pane-resizer-id="${id}"]`) as HTMLElement;
```
Comment (songpola) [inline packages/paneforge/src/lib/internal/helpers.ts:304]: And this.

**Review by songpola — COMMENTED** [review]
Maybe adding generics to these methods in the `svelte-toolbelt`?
So, we don't have to do the type assertions.
